### PR TITLE
Check Kdump configuration with multiple crashkernel options

### PR DESCRIPTION
**Pull request by imobach**

### CODE REVIEW

**Comment by jreidinger** [comment]
@imobach what is status here?

**Comment by imobach** [comment]
@jreidinger Waiting to finally close autoyast-integration-test refactoring (including VirtualBox support). Hopefully it will be merged today or on monday.

**Comment by imobach** [comment]
This PR should be rebased and merge when outgoing changes on AutoYaST integration tests are finished (hopefully this week).

**Comment by schubi2** [comment]
LGTM

**Comment by imobach** [comment]
Thanks. Merging...

**Pull request merged**
