### PR TITLE
Split framework and tests

### PR DESCRIPTION
**Pull request by imobach**
## About

This is a huge pull request (sorry about that) which aims on splitting AYTests framework and integration test themselves. The objectives of such a change are:

* Ship framework and tests as RPM packages. These packages will be independent so, for example, SLEPOS team could grab only the test to run them in their OpenQA setup.
* Simplify a little bit more the installation of the framework (no bundler or development libraries will be needed).

## Changes

* Added a CLI to interact with the framework instead of relying on Rake. For example:
```
aytests build_iso sles12-sp1
aytests test /path/to/my/test
aytests help
```
* AYTests will use a separated directory (`work directory`) to perform all the actions: downloading ISOs, retrieving packages, building Vagrant boxes, etc. By default `$HOME/aytests-workspace` will be used, but it can be changed easily:
```
aytests build_iso sles12-sp1 --work-dir $HOME/my-workspace
```
* Use command line options instead of environment variables  to configure the behaviour of the framework (although environment variables are still supported).
```
aytests test /path/to/my/test --provider virtualbox --headless
```
* Added support for packaging through `packaging_rake_tasks`. So `rake tarball` or `rake osc:build` will work as expected. Anyway, old Rake tasks are still supported but deprecated: they'll be translated to `aytests` invocations.
* Tests are now independent and live in [imobach/aytests-tests](http://github.com/imobach/aytests-tests) repository. They should be moved to yast/aytests-tests.

## Notes

* [net-ssh-simple](https://build.opensuse.org/package/show/home:IGonzalezSosa:ruby/rubygem-net-ssh-simple) is a dependency of `rubygem-aytests` and, as long as it's not included in `devel:languages:ruby:extensions`, it should be installed from [home:IGonzalezSosa:ruby](https://build.opensuse.org/project/show/home:IGonzalezSosa:ruby) repository.
* [Veewee](https://github.com/jedi4ever/veewee) is also a dependency, but it's not available in openSUSE/SUSE. That software has a lot of dependencies and creating a package will be a very time-consuming task. So I've decided to install it using `rubygems` into the user directory to avoid conflicts with other gems). `aytests setup` will take care of that.

### CODE REVIEW

**Comment by schubi2** [comment]
Hm, I would not set the default to $HOME/my-workspace because it could be very restricted.
Could we move it e.g. /usr/local ?
But in general...really nice !

**Comment by imobach** [comment]
@schubi2 Yes, you're right, but I was using a directory into $HOME because, if you run aytests as a regular user, it's the only place when you're supposed to have writing permissions.

**Comment by schubi2** [comment]
OK, thats an argument. Lets try it ! --> LGTM

**Comment by imobach** [comment]
Thanks!

**Pull request merged**
