### PR TITLE
Run 'vagrant destroy' before removing the libvirt image

### PR DESCRIPTION
**Pull request by imobach**

### CODE REVIEW

**Comment by schubi2** [comment]
Hm, I am not sure to destroy all the stuff completely. May be that someone has defined an own VM outside of AutoYaST which he would like to use and not to destroy?

**Comment by imobach** [comment]
Only the vagrant machines defined in our `Vagrantfile` will be destroyed. But just to be sure, I'll just destroy `autoyast_vm` machine.

**Comment by schubi2** [comment]
OK, if you are sure :-) ....LGTM

**Comment by imobach** [comment]
Yes, I'm pretty sure about that :) Anyway, adding the machine name will make it more clear for us.

**Comment by imobach** [comment]
Thanks!

**Pull request merged**
